Hades.Web/Controllers/CampanhaController.cs
using Hades.Application.Interface;
using Hades.Domain.Entities;
using Hades.Web.ViewModels;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Hades.Web.Controllers
{
    public class CampanhaController : BaseController
    {
        private readonly ICampanhaAppService _campanhaAppService;
        private readonly ICampanhaParticipanteAppService _campanhaParticipanteAppService;
        private readonly IUsuarioAppService _usuarioAppService;

        public CampanhaController(ICampanhaAppService campanhaAppService, ICampanhaParticipanteAppService campanhaParticipanteAppService, IUsuarioAppService usuarioAppService)
        {
            _campanhaAppService = campanhaAppService;
            _campanhaParticipanteAppService = campanhaParticipanteAppService;
            _usuarioAppService = usuarioAppService;
        }

        public ActionResult Index()
        {
            ViewBag.NomeUsuario = Session["Nome"].ToString();
            return View();
        }

        public ActionResult BuscaGridCampanhas()
        {
            var campanhaViewModel = _campanhaAppService.GetCampanhas((int)Session["IdUsuario"]);
            if (!campanhaViewModel.IsSuccessStatusCode)
                return ErrorMessage("Erro ao trazer campanhas");
            var campanha = JsonConvert.DeserializeObject<IEnumerable<CampanhaViewModel>>(campanhaViewModel.Content.ReadAsStringAsync().Result);
            return View("_TabelaCampanha", campanha);
        }

        public ActionResult BuscaGridTodasCampanhas()
        {
            var campanhaViewModel = _campanhaAppService.GetTodasCampanhas((int)Session["IdUsuario"]);
            if (!campanhaViewModel.IsSuccessStatusCode)
                return ErrorMessage("Erro ao trazer campanhas");
            var campanha = JsonConvert.DeserializeObject<IEnumerable<CampanhaViewModel>>(campanhaViewModel.Content.ReadAsStringAsync().Result);
            return View("_TabelaCampanha", campanha);
        }

        public ActionResult Details(int idCampanha)
        {
            var campanha = _campanhaAppService.GetCampanha(idCampanha);
            if (!campanha.IsSuccessStatusCode)
                return ErrorMessage("Erro ao trazer Campanha");
            var mostraCampanha =
                JsonConvert.DeserializeObject<CampanhaViewModel>(campanha.Content.ReadAsStringAsync().Result);

            return View(mostraCampanha);
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult CreateConfirmed(CampanhaDto campanha)
        {
            var response = _campanhaAppService.Post(campanha);
            return response.IsSuccessStatusCode ? Json("OK") : ErrorMessage("Erro ao criar Campanha");
        }

        public ActionResult Edit(int idCampanha)
        {
            var response = _campanhaAppService.GetCampanha(idCampanha);
            if (!response.IsSuccessStatusCode)
                return ErrorMessage("Erro ao trazer campanha");
            var campanha = JsonConvert.DeserializeObject<CampanhaViewModel>(response.Content.ReadAsStringAsync().Result);

            return View(campanha);
        }

        public ActionResult EditConfirmed(CampanhaDto campanha)
        {
            var response = _campanhaAppService.Put(campanha);
            return response.IsSuccessStatusCode ? Json("OK") : ErrorMessage("Erro ao editar campanha");
        }

        public ActionResult Delete(int idCampanha)
        {
            var retorno = _campanhaAppService.Delete(idCampanha);
            return !retorno.IsSuccessStatusCode ? ErrorMessage("Erro ao deletar campanha") : Json("OK");
        }
    }
}

Hades.Web/Controllers/EnqueteController.cs
using Hades.Application.Interface;
using Hades.Domain.Entities;
using Hades.Web.ViewModels;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Hades.Web.Controllers
{
    public class EnqueteController : BaseController
    {
        private readonly IEnqueteAppService _enqueteAppService;
        private readonly IVotacaoAppService _votacaoAppService;

        public EnqueteController(IEnqueteAppService enqueteAppService, IVotacaoAppService votacaoAppService)
        {
            _enqueteAppService = enqueteAppService;
            _votacaoAppService = votacaoAppService;
        }

        // GET: Enquete
        public ActionResult Index()
        {
            ViewBag.NomeUsuario = Session["Nome"];
            ViewBag.Adm = Session["Administrador"];
            return View();
        }

        public ActionResult BuscaGridEnquetes()
        {
            var usuarioViewModel = _enqueteAppService.GetAll();
            if (!usuarioViewModel.IsSuccessStatusCode)
                return ErrorMessage("Erro ao trazer lista de enquetes.");

            var enquetes = JsonConvert.DeserializeObject<IEnumerable<EnqueteViewModel>>(usuarioViewModel.Content.ReadAsStringAsync().Result);

            return View("_TabelaEnquetes", enquetes);
        }

        public ActionResult BuscaGridTodasEnquetes()
        {
            var usuarioViewModel = _enqueteAppService.GetTodasEnquetes();
            if (!usuarioViewModel.IsSuccessStatusCode)
                return ErrorMessage("Erro ao trazer lista de enquetes.");

            var enquetes = JsonConvert.DeserializeObject<IEnumerable<EnqueteViewModel>>(usuarioViewModel.Content.ReadAsStringAsync().Result);

            return View("_TabelaEnquetes", enquetes);
        }

        // GET: Enquete/Details/5
        public ActionResult Details(int id)
        {
            var enquete = _enqueteAppService.GetById(id);
            if (!enquete.IsSuccessStatusCode)
                return ErrorMessage("Erro ao buscar enquete");

            var mostraEnquete =
                JsonConvert.DeserializeObject<EnqueteViewModel>(enquete.Content.ReadAsStringAsync().Result);

            return View(mostraEnquete);
        }

        // GET: Enquete/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Enquete/Create
        public ActionResult CreateConfirmed(EnqueteDto enquete)
        {
            var request = _enqueteAppService.GetAll();
            if (!request.IsSuccessStatusCode)
                return ErrorMessage("Erro ao verificar se usuário já existe");

            var enqueteViewModel = JsonConvert.DeserializeObject<IEnumerable<EnqueteViewModel>>(request.Content.ReadAsStringAsync().Result);

            var verifica = enqueteViewModel.Select(x => x.Assunto.Contains(enquete.Assunto)).ToString();

            if (string.IsNullOrEmpty(verifica))
                return ErrorMessage("Enquete já existe, insira outro título.");

            var response = _enqueteAppService.Post(enquete);
            if (!response.IsSuccessStatusCode)
                ErrorMessage("Erro ao criar enquete");

            return Json("Cadastro Efetuado com sucesso");
        }

        // GET: Enquete/Edit/5
        public ActionResult Edit(int id)
        {
            var response = _enqueteAppService.GetById(id);
            if (!response.IsSuccessStatusCode)
                return ErrorMessage("Erro ao buscar enquete.");
            var enquete = JsonConvert.DeserializeObject<EnqueteViewModel>(response.Content.ReadAsStringAsync().Result);
            return View(enquete);
        }

        // POST: Enquete/Edit/5
        public ActionResult EditConfirmed(EnqueteDto enquete)
        {
            //Valor com . precisa conter o ModelBinder, senão, ele nao salvará corretamente
            var response = _enqueteAppService.Put(enquete);
            if (response.IsSuccessStatusCode)
                return Json("Enquete Atualizada com sucesso");
            return ErrorMessage($"Erro ao editar enquete: {response.Content.ReadAsStringAsync().Result}");
        }

        public ActionResult DesativarEnquete(int id)
        {
            var response = _enqueteAppService.StatusEnquete(id);
            if (response.IsSuccessStatusCode)
                return RedirectToAction("BuscaGridEnquetes");
            return ErrorMessage("Erro ao desativar Enquete");

        }

        public ActionResult GetVotacao(Votacao votacao)
        {
            var response = _votacaoAppService.GetVotos(votacao.IdUsuario, votacao.IdEnquete);

            if (!response.IsSuccessStatusCode)
                return ErrorMessage("Não foi possível efetuar votação. Faça o Log In novamente!");

            var voto = JsonConvert.DeserializeObject<Votacao>(response.Content.ReadAsStringAsync().Result);

            if (voto == null)
                voto = new Votacao { Enquete = votacao.Enquete, IdEnquete = votacao.IdEnquete, IndicadorCadastro = "S" };
            else
            {
                voto.Enquete = votacao.Enquete;
                voto.IdEnquete = votacao.IdEnquete;
                voto.IndicadorCadastro = "N";
            }

            return RedirectToAction("Create", "Votacao", voto);
        }
    }
}

Hades.Web/Controllers/LoginController.cs
using Hades.Application.Interface;
using Hades.Domain.Entities;
using Hades.Web.ViewModels;
using Newtonsoft.Json;
using System.Web.Mvc;

namespace Hades.Web.Controllers
{
    public class LoginController : BaseController
    {
        private readonly IUsuarioAppService _usuarioAppService;

        public LoginController(IUsuarioAppService usuarioAppService)
        {
            _usuarioAppService = usuarioAppService;
        }

        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult VerificarLogin(string nome, string senha)
        {
            if (!string.IsNullOrEmpty(nome) || !string.IsNullOrEmpty(senha))
            {
                var usuarioViewModel = _usuarioAppService.GetByName(Server.UrlEncode(nome));
                //UrlEncode serve para transformar em string para ser passado na URL
                if (!usuarioViewModel.IsSuccessStatusCode)
                {
                    TempData["mensagem"] = "Erro ao fazer busca no banco de dados!";
                    return RedirectToAction("Index");
                }
                var mostraUsuario = JsonConvert.DeserializeObject<UsuarioViewModel>(usuarioViewModel.Content.ReadAsStringAsync().Result);

                if (mostraUsuario == null)
                {
                    TempData["mensagem"] = "Usuario Inexistente!";
                    return RedirectToAction("Index");
                }

                var verifica = _usuarioAppService.SenhaFormatada(senha);

                if (!verifica.IsSuccessStatusCode)
                {
                    TempData["mensagem"] = "Erro ao verificar Senha!";
                    return RedirectToAction("Index");
                }

                var verificaSenha = JsonConvert.DeserializeObject(verifica.Content.ReadAsStringAsync().Result).ToString();

                if (mostraUsuario.Senha != verificaSenha)
                {
                    TempData["mensagem"] = "Senha não confere com o Usuário";
                    return RedirectToAction("Index");
                }

                if (!mostraUsuario.Ativo)
                {
                    TempData["mensagem"] = "Usuario desativado, contate o Administrador!";
                    return RedirectToAction("Index");
                }

                if (string.IsNullOrEmpty(nome) || string.IsNullOrEmpty(senha))
                {
                    TempData["mensagem"] = "Usuario Inexistente!";
                    return RedirectToAction("Index");
                }

                Session["IdUsuario"] = mostraUsuario.Id;
                Session["Nome"] = mostraUsuario.Nome;
                Session["Administrador"] = mostraUsuario.Administrador;

                return RedirectToAction("Index", "Home");

            }
            TempData["mensagem"] = "Login e Senha Incorretos!";
            return RedirectToAction("Index");
        }

        public ActionResult CreateUsuario()
        {
            return View();
        }

        // POST: Usuario/Create
        public ActionResult CreateConfirmed(Usuario usuario)
        {
            var request = _usuarioAppService.GetByName(usuario.Nome);
            if (!request.IsSuccessStatusCode)
                return ErrorMessage("Erro ao verificar se usuário já existe");

            var usuarioViewModel = JsonConvert.DeserializeObject<Usuario>(request.Content.ReadAsStringAsync().Result);

            if (usuarioViewModel != null)
                if (usuario.Nome == usuarioViewModel.Nome)
                    return ErrorMessage("Usuario já existe, insira outro nome.");

            var response = _usuarioAppService.Post(usuario);
            if (response.IsSuccessStatusCode)
                return Json("OK");
            return ErrorMessage($"Erro ao criar usuario: {response.Content.ReadAsStringAsync().Result}");
        }
    }
}

Hades.Web/Controllers/UsuarioController.cs
using Hades.Application.Interface;
using Hades.Domain.Entities;
using Hades.Web.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Hades.Web.Controllers
{
    public class UsuarioController : BaseController
    {
        private readonly IUsuarioAppService _usuarioAppService;

        public UsuarioController(IUsuarioAppService usuarioAppService)
        {
            _usuarioAppService = usuarioAppService;
        }

        // GET: Usuario
        public ActionResult Index()
        {
            ViewBag.NomeUsuario = Session["Nome"];
            return View();
        }

        // GET: Usuario/Details/5
        public ActionResult Details(int id)
        {
            var usuario = _usuarioAppService.GetById(id);
            if (!usuario.IsSuccessStatusCode)
                return ErrorMessage("Erro ao trazer Usuario");
            var mostraUsuario =
                JsonConvert.DeserializeObject<UsuarioViewModel>(usuario.Content.ReadAsStringAsync().Result);

            return View(mostraUsuario);
        }

        // GET: Usuario/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Usuario/Create
        public ActionResult CreateConfirmed(Usuario usuario)
        {
            var request = _usuarioAppService.GetByName(usuario.Nome);
            if (!request.IsSuccessStatusCode)
                return ErrorMessage("Erro ao verificar se usuário já existe");

            var usuarioViewModel = JsonConvert.DeserializeObject<Usuario>(request.Content.ReadAsStringAsync().Result);

            if (usuarioViewModel != null)
                if (usuario.Nome == usuarioViewModel.Nome)
                    return ErrorMessage("Usuario já existe, insira outro nome.");

            var response = _usuarioAppService.Post(usuario);
            return response.IsSuccessStatusCode
                ? Json("Cadastro Efetuado com sucesso")
                : ErrorMessage($"Erro ao criar usuario: {response.Content.ReadAsStringAsync().Result}");
        }

        // GET: Usuario/Edit/5
        public ActionResult Edit(int id)
        {
            var response = _usuarioAppService.GetById(id);
            if (!response.IsSuccessStatusCode)
                return ErrorMessage("Erro ao buscar usuario");
            var usuario = JsonConvert.DeserializeObject<Usuario>(response.Content.ReadAsStringAsync().Result);
            return View(new UsuarioViewModel(usuario));
        }

        // PUT: Usuario/Edit/5
        public ActionResult EditConfirmed(Usuario usuario)
        {
            var response = _usuarioAppService.Put(usuario);
            return response.IsSuccessStatusCode
                ? Json("Cadastro Atualizado com sucesso")
                : ErrorMessage($"Erro ao editar usuario: {response.Content.ReadAsStringAsync().Result}");
        }

        public ActionResult BuscaGridUsuario()
        {
            var usuarioViewModel = _usuarioAppService.GetAll();
            if (!usuarioViewModel.IsSuccessStatusCode)
                return ErrorMessage("Erro ao buscar usuarios.");
            var usuarios =
                JsonConvert.DeserializeObject<IEnumerable<UsuarioViewModel>>(usuarioViewModel.Content.ReadAsStringAsync().Result);

            ViewBag.Title = "HADES";
            ViewBag.NomeUsuario = Session["Nome"];

            return View("_TabelaUsuarios", usuarios);
        }

        public ActionResult AtivarUsuario(int id)
        {
            try
            {
                var response = _usuarioAppService.StatusUsuario(id, true);
                if (!response.IsSuccessStatusCode)
                    return ErrorMessage("Erro ao alterar o usuario");
                return RedirectToAction("BuscaGridUsuario");
            }
            catch (Exception e)
            {

                return ErrorMessage("Erro ao alterar o usuario, " + e.Message);
            }
        }

        public ActionResult DesativarUsuario(int id)
        {
            var response = _usuarioAppService.StatusUsuario(id, false);
            if (!response.IsSuccessStatusCode)
                return ErrorMessage("Erro ao alterar o usuario");
            return RedirectToAction("BuscaGridUsuario");
        }
    }
}

Hades.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>EUDORA</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <script src="~/Scripts/Common.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    @RenderSection("scripts", required: false)
    <style>
        .nav-gradient {
            /*height: 70px;*/
            background: #455a64; /* For browsers that do not support gradients */
            background: -webkit-linear-gradient(black, #455a64); /* For Safari 5.1 to 6.0 */
            background: -o-linear-gradient(black, #455a64); /* For Opera 11.1 to 12.0 */
            background: -moz-linear-gradient(black, #455a64); /* For Firefox 3.6 to 15 */
            background: linear-gradient(black, #455a64); /* Standard syntax (must be last) */
        }

    </style>
</head>
<body style="background-color: #455a64; padding-top: 0px;">
    <nav style="height: 75px;">
        <div class="nav-wrapper accent-4 nav-gradient" style="background-color: #455a64;">
            <img src="~/images/EUDORA.png" style="margin-left: 20px; width: 75px;">
            <label id="LayoutNomeUsuarioLogado" style="text-align: center; font-size: 1rem; color: white; position: relative; top: -29px;"></label>

            <a href="#" data-activates="mobile-demo" class="button-collapse">
                <i class="material-icons" style="font-size: 40px;color: white;border-radius: 40px;width: 5px;height: 55px;position: relative;top: 10px;">reorder</i>
            </a>
            <ul id="nav-mobile" class="right hide-on-med-and-down" style="margin-top: 10px;">
                <li><a style="font-size: large; color: white" href="@Url.Action("Index", "Usuario")">USUÁRIO</a></li>
                <li><a style="font-size: large; color: white" href="@Url.Action("Index", "Campanha")">CAMPANHA</a></li>
                <li><a style="font-size: large; color: white" href="@Url.Action("Index", "Enquete")">ENQUETE</a></li>
                <li><a style="font-size: large; color: white" href="@Url.Action("Index", "Sorteio")">SORTEIO</a></li>
                <li><a style="font-size: large; color: white" href="@Url.Action("Index", "Login")">SAIR</a></li>
            </ul>
            <ul class="side-nav" id="mobile-demo">
                <li><a href="@Url.Action("Index", "Usuario")">USUÁRIO</a></li>
                <li><a href="@Url.Action("Index", "Campanha")">CAMPANHA</a></li>
                <li><a href="@Url.Action("Index", "Enquete")">ENQUETE</a></li>
                <li><a href="@Url.Action("Index", "Sorteio")">SORTEIO</a></li>
                <li><a href="@Url.Action("Index", "Login")">SAIR</a></li>
            </ul>
        </div>
    </nav>
    <div class="container" id="divContainerPrincipal">
        @RenderBody()
        <footer>
            @*<p>&copy; @DateTime.Now.Year - HADES Application</p>*@
        </footer>
    </div>
</body>
</html>

<script>
    var nomeUsuario = sessionStorage.getItem('NomeUsuarioLogado');
    $(document).ready(function () {
        $(".button-collapse").sideNav();
        $("#LayoutNomeUsuarioLogado").text(nomeUsuario.toUpperCase());
    });
</script>

Hades.Web/Views/Shared/_LayoutSemNavBar.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">    
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css"/>
    <script src="~/Scripts/Common.js"></script>
    @RenderSection("scripts", required: false)
</head>
<body style="background-color: white;">
    <div class="container">

        @RenderBody()
        @*<hr style="color: black"/>*@
        <footer>
            @*<p>&copy; @DateTime.Now.Year - HADES Application</p>*@
        </footer>
    </div>
</body>
</html>

Hades.Web/Views/Shared/_LayoutUsuario.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>EUDORA</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css"/>
    <script src="~/Scripts/Common.js"></script>
    @RenderSection("scripts", required: false)

    <style>
        .nav-gradient {
            /*height: 70px;*/
            background: #455a64; /* For browsers that do not support gradients */
            background: -webkit-linear-gradient(black, #455a64); /* For Safari 5.1 to 6.0 */
            background: -o-linear-gradient(black, #455a64); /* For Opera 11.1 to 12.0 */
            background: -moz-linear-gradient(black, #455a64); /* For Firefox 3.6 to 15 */
            background: linear-gradient(black, #455a64); /* Standard syntax (must be last) */
        }
    </style>

</head>
<body style="background-color: #455a64; padding-top: 0px;">
    <nav style="height: 75px;">
        <div class="nav-wrapper accent-4 nav-gradient" style="background-color: #455a64;">
            <img src="~/images/EUDORA.png" style="margin-left: 20px; width: 75px;">
            <label id="LayoutNomeUsuarioLogado" style="text-align: center; font-size: 1rem; color: white; position: relative; top: -29px;"></label>

            <a href="#" data-activates="mobile-demo" class="button-collapse">
                <i class="material-icons" style="font-size: 40px;color: white; border-radius: 40px;width: 5px;height: 55px;position: relative;top: 10px;">reorder</i>
            </a>
            <ul id="nav-mobile" class="right hide-on-med-and-down" style="margin-top: 10px;">
                <li><a style="font-size: large; color: white" href="@Url.Action("Index", "Campanha")">CAMPANHA</a></li>
                <li><a style="font-size: large; color: white" href="@Url.Action("Index", "Enquete")">ENQUETE</a></li>
                <li><a style="font-size: large; color: white" href="@Url.Action("Index", "Sorteio")">SORTEIO</a></li>
                <li><a style="font-size: large; color: white" href="@Url.Action("Index", "Login")">SAIR</a></li>
            </ul>
            <ul class="side-nav" id="mobile-demo">
                <li><a href="@Url.Action("Index", "Campanha")">CAMPANHA</a></li>
                <li><a href="@Url.Action("Index", "Enquete")">ENQUETE</a></li>
                <li><a href="@Url.Action("Index", "Sorteio")">SORTEIO</a></li>
                <li><a href="@Url.Action("Index", "Login")">SAIR</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">

        @RenderBody()
        <footer>
            @*<p>&copy; @DateTime.Now.Year - HADES Application</p>*@
        </footer>
    </div>
</body>
</html>

<script>
    var nomeUsuario = sessionStorage.getItem('NomeUsuarioLogado');
    $(document).ready(function () {
        $(".button-collapse").sideNav();
        $("#LayoutNomeUsuarioLogado").text(nomeUsuario.toUpperCase());
    });
</script>