Hades.Web/ViewModels/SorteioViewModel.cs
using System;
using System.Collections.Generic;

namespace Hades.Web.ViewModels
{
    public class SorteioViewModel
    {
        public SorteioViewModel()
        {
            SorteioParticipantes = new List<SorteioParticipanteViewModel>();
        }

        public int Id { get; set; }
        public string Nome { get; set; }
        public int QtdParticipantes { get; set; }
        public int IdCriador { get; set; }
        public string NomeCriador { get; set; }
        public bool Adm { get; set; }
        public DateTime DataSorteio { get; set; }
        public string DataFormatada => $"{DataSorteio:dd/MM/yyyy}";
        public int QtdeItens { get; set; }
        public string IndParticipante { get; set; }
        public bool Ativo { get; set; }
        public bool FoiSorteado { get; set; }

        public List<SorteioParticipanteViewModel> SorteioParticipantes { get; set; }
    }
}

Hades.Web/Controllers/SorteioController.cs
using Hades.Application;
using Hades.Application.Interface;
using Hades.Domain.Entities;
using Hades.Web.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web.Mvc;

namespace Hades.Web.Controllers
{
    public class SorteioController : BaseController
    {
        private readonly ISorteioAppService _sorteioAppService;
        private readonly ISorteioParticipanteAppService _sorteioParticipanteAppService;
        private readonly IUsuarioAppService _usuarioAppService;

        public SorteioController(ISorteioAppService sorteioAppService, ISorteioParticipanteAppService sorteioParticipanteAppService, UsuarioAppService usuarioAppService)
        {
            _sorteioAppService = sorteioAppService;
            _sorteioParticipanteAppService = sorteioParticipanteAppService;
            _usuarioAppService = usuarioAppService;
        }
        
        public ActionResult Index()
        {
            ViewBag.NomeUsuario = Session["Nome"].ToString();
            return View();
        }

        public ActionResult BuscaGridSorteios()
        {
            var sorteioViewModel = _sorteioAppService.GetAll((int)Session["IdUsuario"]);
            if (!sorteioViewModel.IsSuccessStatusCode)
                return ErrorMessage("Erro ao trazer sorteios");
            var sorteio = 
                JsonConvert.DeserializeObject<IEnumerable<SorteioViewModel>>(sorteioViewModel.Content.ReadAsStringAsync().Result);
            return View("_TabelaSorteio", sorteio);
        }

        public ActionResult BuscaGridTodosSorteios()
        {
            var sorteioViewModel = _sorteioAppService.GetTodosSorteios((int)Session["IdUsuario"]);
            if (!sorteioViewModel.IsSuccessStatusCode)
                return ErrorMessage("Erro ao trazer sorteios");
            var sorteio =
                JsonConvert.DeserializeObject<IEnumerable<SorteioViewModel>>(sorteioViewModel.Content.ReadAsStringAsync().Result);
            return View("_TabelaSorteio", sorteio);
        }

        public ActionResult Details(int id)
        {
            var sorteio = _sorteioAppService.GetById(id);
            if (!sorteio.IsSuccessStatusCode)
                return ErrorMessage("Erro ao trazer sorteio");
            var mostraSorteio =
                JsonConvert.DeserializeObject<SorteioViewModel>(sorteio.Content.ReadAsStringAsync().Result);

            return View(mostraSorteio);
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult CreateConfirmed(SorteioDto sorteio)
        {
            var response = _sorteioAppService.Post(sorteio);
            if (response.IsSuccessStatusCode)
                return Json("OK");
            return ErrorMessage("Erro ao criar Sorteio");
        }

        public ActionResult Edit(int id)
        {
            var response = _sorteioAppService.GetById(id);
            if (!response.IsSuccessStatusCode)
                return ErrorMessage("Erro ao trazer sorteio");
            var sorteio = JsonConvert.DeserializeObject<SorteioViewModel>(response.Content.ReadAsStringAsync().Result);

            return View(sorteio);
        }

        public ActionResult EditConfirmed(SorteioDto sorteio)
        {
            var response = _sorteioAppService.Put(sorteio);
            if (response.IsSuccessStatusCode)
                return RedirectToAction("Index");
            return ErrorMessage("Erro ao editar sorteio");
        }

        public ActionResult Delete(int id)
        {
            var retorno = _sorteioAppService.Delete(id);
            if (!retorno.IsSuccessStatusCode)
                return ErrorMessage("Erro ao deletar sorteio");
            var response = _sorteioAppService.GetAll((int)Session["IdUsuario"]);
            var sorteio = JsonConvert.DeserializeObject<IEnumerable<SorteioViewModel>>(response.Content.ReadAsStringAsync().Result);
            return View("_TabelaSorteio", sorteio);
        }

        public ActionResult Drawlots(int idSorteio)
        {
            var responseParticipantes = _sorteioAppService.GetById(idSorteio);

            if (!responseParticipantes.IsSuccessStatusCode)
                return ErrorMessage("Erro ao trazer participantes");


            var dadosParticipantesSorteio = JsonConvert.DeserializeObject<SorteioViewModel>
                        (responseParticipantes.Content.ReadAsStringAsync().Result);

            if (!dadosParticipantesSorteio.SorteioParticipantes.Any())
                return ErrorMessage("Não foi encontrado nenhum participante");

            if (dadosParticipantesSorteio.QtdParticipantes <= dadosParticipantesSorteio.QtdeItens)
            {
                foreach (var vencedor in dadosParticipantesSorteio.SorteioParticipantes)
                {
                    _sorteioParticipanteAppService.VencedorParticipantesSorteio(idSorteio, vencedor.Id_Participante);

                    var sorteado = _usuarioAppService.GetByName(vencedor.Nome_Participante);
                    var sorteadoEmail = JsonConvert.DeserializeObject<UsuarioViewModel>(sorteado.Content.ReadAsStringAsync().Result);

                    EnviarEmail(sorteadoEmail.Email, sorteadoEmail.Nome, dadosParticipantesSorteio.Nome, dadosParticipantesSorteio.NomeCriador);
                }
                return View(dadosParticipantesSorteio); ;
            }

            var aleatorio = new Random();
            var participantes = dadosParticipantesSorteio.SorteioParticipantes;
            var vencedores = new string[dadosParticipantesSorteio.QtdeItens];
            var contadorRotina = 0;
            var posicoesSorteadas = new int?[dadosParticipantesSorteio.QtdeItens];

            var sortearNovamente = _sorteioParticipanteAppService.SortearNovamente(idSorteio);
            if (!sortearNovamente.IsSuccessStatusCode)
                return ErrorMessage("Erro ao zerar Vencedores");

            do
            {
                var posicao = aleatorio.Next(0, participantes.Count);
                if (!posicoesSorteadas.Contains(posicao))
                {
                    posicoesSorteadas[contadorRotina] = posicao;
                    vencedores[contadorRotina] = participantes[posicao].Nome_Participante;
                    dadosParticipantesSorteio.QtdeItens -= 1;
                    _sorteioParticipanteAppService.VencedorParticipantesSorteio(idSorteio, participantes[posicao].Id_Participante);
                    contadorRotina++;

                    var sorteado = _usuarioAppService.GetByName(participantes[posicao].Nome_Participante);
                    var sorteadoEmail = JsonConvert.DeserializeObject<UsuarioViewModel>(sorteado.Content.ReadAsStringAsync().Result);

                    EnviarEmail(sorteadoEmail.Email, sorteadoEmail.Nome, dadosParticipantesSorteio.Nome, participantes[posicao].Sorteio.NomeCriador);
                }
            } while (dadosParticipantesSorteio.QtdeItens > 0);

            var getVencedores = new SorteioViewModel { Nome = dadosParticipantesSorteio.Nome };
            foreach (var vencedor in vencedores)
            {
                getVencedores.SorteioParticipantes.Add(new SorteioParticipanteViewModel { Nome_Participante = vencedor });
            }

            return View(getVencedores);
        }

        //private void EnviarEmail(string email, string nomeGanhador, string nomSorteio, string nomeCriadorSorteio)
        //{
        //    var client = new SmtpClient("smtp.gmail.com", 587)
        //    {
        //        Host = "smtp.gmail.com",
        //        EnableSsl = true,
        //        Credentials = new System.Net.NetworkCredential("hades.suporte.2017@gmail.com", "hades2017")
        //    };

        //    var mail = new MailMessage
        //    {
        //        Sender = new MailAddress($"{email}", $"{nomeGanhador}"),
        //        From = new MailAddress("hades.suporte.2017@gmail.com", "HADES")
        //    };

        //    mail.To.Add(new MailAddress($"{email}", $"{nomeGanhador}"));
        //    mail.Subject = "Contato Sorteio";
        //    mail.Body = $"Mensagem do site:<br/> HADES<br/><br/> Mensagem : <br>   Parabéns {nomeGanhador}, você acabou de ganhar no sorteio: {nomSorteio}, " +
        //        $"um(a) ótimo(a) item, entre em contato com o {nomeCriadorSorteio}, e resgate seu prêmio." +
        //        "<br/><br/><br/><br/><br/><br/><br/> Atenciosamente, Equipe HADES.";
        //    mail.IsBodyHtml = true;

        //    client.Send(mail);
        //}

        private void EnviarEmail(string email, string nomeGanhador, string nomSorteio, string nomeCriadorSorteio)
        {
            var body = $"Mensagem do site:<br/> HADES<br/><br/> Mensagem : <br>   Parabéns {nomeGanhador}, você acabou de ganhar no sorteio: {nomSorteio}, " +
               $"um(a) ótimo(a) item, entre em contato com o {nomeCriadorSorteio}, e resgate seu prêmio." +
               "<br/><br/><br/><br/><br/><br/> Atenciosamente,<br/> Equipe HADES.";

            var client = new SmtpClient("smtp.gmail.com", 587)
            {
                EnableSsl = true,
                Credentials = new System.Net.NetworkCredential("hades.suporte.2017@gmail.com", "hades2017")
            };
            client.Send(new MailMessage(new MailAddress($"{email}", "HADES"), new MailAddress($"{email}", $"{nomeGanhador}"))
            {
                Subject = "Contato Sorteio",
                Body = body,
                IsBodyHtml = true
            });
        }

        public ActionResult Winners(int idSorteio)
        {
            var vencedores = _sorteioParticipanteAppService.GetVencedores(idSorteio);
            if (!vencedores.IsSuccessStatusCode)
                return ErrorMessage("Erro ao buscar vencedores");

            var sorteio = JsonConvert.DeserializeObject<IEnumerable<SorteioParticipanteViewModel>>(vencedores.Content.ReadAsStringAsync().Result);

Hades.Web/Controllers/SorteioParticipantesController.cs
using Hades.Application.Interface;
using Hades.Web.ViewModels;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Hades.Web.Controllers
{
    public class SorteioParticipantesController : BaseController
    {
        private readonly ISorteioParticipanteAppService _sorteioParticipanteAppService;

        public SorteioParticipantesController(ISorteioParticipanteAppService sorteioParticipanteAppService)
        {
            _sorteioParticipanteAppService = sorteioParticipanteAppService;
        }

        // GET: SorteioParticipantes
        public ActionResult Participar(int idSorteio, int idUsuario)
        {
            var response = _sorteioParticipanteAppService.Participar(idSorteio, idUsuario);
            if (!response.IsSuccessStatusCode)
                return ErrorMessage("Erro ao ativar participante, tente novamente");

            return Json("Sucesso, participante incluido com sucesso!", JsonRequestBehavior.AllowGet);
        }

        // GET: SorteioParticipantes/Create
        public IEnumerable<SorteioParticipanteViewModel> GetAll(int id)
        {
            var response = _sorteioParticipanteAppService.GetAll(id);
            var participantes =
                JsonConvert.DeserializeObject<IEnumerable<SorteioParticipanteViewModel>>(response.Content.ReadAsStringAsync().Result);
            return participantes;
        }

        public ActionResult DeletarParticipante(int idSorteio, int idUsuario)
        {
            var response = _sorteioParticipanteAppService.DeletarParticipantesSorteio(idSorteio, idUsuario);
            if (!response.IsSuccessStatusCode)
                return ErrorMessage("Erro ao alterar o usuario");
            return Json("Sucesso, participante excluido com sucesso!", JsonRequestBehavior.AllowGet);
        }

    }
}

Hades.Web/Views/Sorteio/Create.cshtml
@model Hades.Web.ViewModels.SorteioViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutSemNavBar.cshtml";
}

<div class="row" style="margin-top: 12px">
    <div class="col s12">
        <div class="row">
            <h4>NOVO SORTEIO</h4>

            @using (Html.BeginForm("CreateConfirmed", "Sorteio", FormMethod.Post, new { @class = "well" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <div class="input-field col s12">
                        <input id="NomeSorteio" type="text" name="NomeSorteio" maxlength="20" data-length="20"
                               onkeypress="verificaCaracteres(this)">
                        <label for="NomeSorteio">NOME SORTEIO</label>
                    </div>
                    <div class="input-field col s12">
                        <input id="DataSorteio" type="text" name="DataSorteio" min="@DateTime.Now" class="datepicker"/>
                        <label for="DataSorteio">DATA SORTEIO</label>
                    </div>
                    <div class="input-field col s12">
                        <input id="QtdeItens" type="number" name="QtdeItens" min="1" max="100" maxlength="3"/>
                        <label for="QtdeItens">QTDE DE ITENS</label>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="button" value="CRIAR" class="btn btn-confirm waves-effect" id="btnCriarSorteio" style="border-radius: 20px;"/>
                        </div>
                    </div>
                </div>
            }
            <div style="margin-left: 110px; margin-top: -36px;">
                <button class="btn btn-default waves-effect" style="float: right" onclick="escondeModal()">CANCELAR</button>
            </div>
        </div>
    </div>
</div>
<script>

    var usuarioLogado = sessionStorage.getItem("IdUsuarioLogado");

    $(document).ready(function () {
        $('input#input_text, textarea#textarea1').characterCounter();
        $('.datepicker').pickadate({
            monthsFull: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
            monthsShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
            weekdaysFull: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
            weekdaysShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
            today: 'Hoje',
            clear: 'Limpar',
            close: 'Pronto',
            labelMonthNext: 'Próximo mês',
            labelMonthPrev: 'Mês anterior',
            labelMonthSelect: 'Selecione um mês',
            labelYearSelect: 'Selecione um ano',
            selectMonths: true,
            selectYears: 15
        });
    });
    
    $("#btnCriarSorteio").click(function () {

        if ($("#NomeSorteio").val().length <= 3) {
            erro("Nome do sorteio tem que estar entre 3 até 20 caracteres");
            return false;
        }

        var dataInput = $("#DataSorteio").val() != "" ? new Date($("#DataSorteio").val()) : "";

        if (dataInput == "" || dataInput < new Date()) {
            erro("Data do Sorteio deve ser maior que hoje");
            return false;
        }

        if ($("#QtdeItens").val() <= 0 || $("#QtdeItens").val() > 100) {
            erro("A quantidade tem que ser maior que zero e menor que 100");
            return false;
        }

        $.post('@Url.Action("CreateConfirmed", "Sorteio")', {
            Nome: $("#NomeSorteio").val(),
            DataSorteio: $("#DataSorteio").val(),
            QtdeItens: $("#QtdeItens").val(),
            IdCriador: usuarioLogado
        }).done(function () {
            escondeModal();
            sucesso("Sorteio cadastrado com Sucesso!");
            buscaTabelaSorteio();
        }).fail(function (xhr) {
            erro(xhr.responseText);
        });
    });

</script>

Hades.Web/Views/Sorteio/Edit.cshtml
@model Hades.Web.ViewModels.SorteioViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutSemNavBar.cshtml";
}

<div class="row" style="margin-top: 12px">
    <div class="col s12">
        <div class="row">
            <h4>NOVO SORTEIO</h4>

            @using (Html.BeginForm("EditConfirmed", "Sorteio", FormMethod.Post, new { @class = "well" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <div class="input-field col s12">
                        <input id="NomeSorteio" type="text" name="NomeSorteio" maxlength="20" data-length="20" value="@Model.Nome"
                               onkeypress="verificaCaracteres(this)">
                        <label for="NomeSorteio">NOME</label>
                    </div>
                    <div class="input-field col s6">
                        <input id="DataSorteio" type="text" name="DataSorteio" style="text-align: center;" class="datepicker"
                               value="@Model.DataFormatada">
                        <label for="DataSorteio">DATA SORTEIO</label>
                    </div>
                    <div class="input-field col s6">
                        <input id="QtdeItens" type="number" style="text-align: center;" name="QtdeItens" maxlength="3" data-length="5" value="@Model.QtdeItens">
                        <label for="QtdeItens">QTDE DE ITENS</label>
                    </div>
                    <div class="form-group">
                        <div class="input-field col s12" style="padding-left: 35%; margin-top: 0; margin-bottom: 20px;">
                            <input type="checkbox" id="Ativo" name="Ativo" @(Model.Ativo ? "checked" : string.Empty) />
                            <label for="Ativo" style="color: black; font-weight: bold;">ATIVO</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="button" value="SALVAR" id="btnSalvarEdicao" class="btn btn-confirm waves-effect" style="border-radius: 20px;" />
                        </div>
                    </div>
                </div>
            }
            <div style="margin-left: 110px; margin-top: -36px;">
                <button class="btn btn-default waves-effect" style="float: right" onclick="escondeModal()">CANCELAR</button>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('input#input_text, textarea#textarea1').characterCounter();
        $('.datepicker').pickadate({
            monthsFull: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
            monthsShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
            weekdaysFull: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
            weekdaysShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
            today: 'Hoje',
            clear: 'Limpar',
            close: 'Pronto',
            labelMonthNext: 'Próximo mês',
            labelMonthPrev: 'Mês anterior',
            labelMonthSelect: 'Selecione um mês',
            labelYearSelect: 'Selecione um ano',
            selectMonths: true,
            selectYears: 15,
            format: 'dd/mm/yyyy'
        });
    });
    
    var IdSorteio = '@Model.Id';

    $("#btnSalvarEdicao").click(function () {
        if ($("#NomeSorteio").val().length <= 3) {
            erro("Nome do sorteio tem que estar entre 3 até 20 caracteres");
            return false;
        }

        var dataInput = $("#DataSorteio").val() != "" ? new Date($("#DataSorteio").val()) : "";

        if (dataInput == "" || dataInput < new Date()) {
            erro("Data do Sorteio deve ser maior que hoje");
            return false;
        }

        if ($("#QtdeItens").val() <= 0 || $("#QtdeItens").val() > 100) {
            erro("A quantidade tem que ser maior que zero e menor que 100");
            return false;
        }

        $.post('@Url.Action("EditConfirmed", "Sorteio")', {
            Id: IdSorteio,
            Nome: $("#NomeSorteio").val(),
            DataSorteio: $("#DataSorteio").val(),
            QtdeItens: $("#QtdeItens").val(),
            Ativo: $("#Ativo").prop("checked")
        }).done(function () {
            escondeModal();
            sucesso("Sorteio editado com Sucesso!");
            buscaTabelaSorteio();
        }).fail(function (xhr) {
            erro(xhr.responseText);
        });
    });

</script>

Hades.Web/Views/Sorteio/Index.cshtml
@using Hades.Web.ViewModels
@model IEnumerable<Hades.Domain.Entities.SorteioDto>

@{
    ViewBag.Title = "Index";
    Layout = (bool)Session["Administrador"] ? "~/Views/Shared/_Layout.cshtml" : "~/Views/Shared/_LayoutUsuario.cshtml"; ;
    var mensagem = TempData["mensagem"]?.ToString() ?? "";
}
<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <div style="background-color: white; padding: 10px; border-radius: 15px; box-shadow: 0 0 30px black; margin-top: 2%;">
        <div style="float: left;">
            <a class="btn-floating red tooltipped waves-effect"  id="Novo" data-position="bottom" data-delay="50" data-tooltip="Criar Sorteio" style="top: 15px;">
                <i class="material-icons">playlist_add</i>
            </a>

            <a class="btn-floating blue-grey tooltipped" data-position="bottom" data-delay="50" id="MudarTabela" data-tooltip="Todos Sorteios" style="top: 15px;">
                <i class="material-icons waves-effect">format_align_justify</i>
            </a>
        </div>

        <h4>LISTA DE SORTEIOS</h4>

        <div id="tabela">
            <div id="tabelaSorteios"></div>
        </div>
    </div>
</div>
<div id="divContentSorteio" class="modal modal-formatada"></div>

<script>

    $("#outros").val()

    var verificaTodasSorteios = false;

    $(".modal-overlay").on("click", function () {
        $(this).hide();
    });

    var mensagemAviso = '@(!string.IsNullOrEmpty(mensagem)?mensagem:"")';

    $(document).ready(function () {
        $('.modal').modal();
        $('.tooltipped').tooltip({ delay: 50 });
        $('input#input_text, textarea#textarea1').characterCounter();
    });

    mensagem(mensagemAviso);

    var urlsSorteio = {
        Edit: '@Url.Action("Edit", "Sorteio")',
        Details: '@Url.Action("Details", "Sorteio")',
        Delete: '@Url.Action("Delete", "Sorteio")',
        Drawlots: '@Url.Action("Drawlots", "Sorteio")',
        Create: '@Url.Action("Create", "Sorteio")',
        BuscaGridSorteios: '@Url.Action("BuscaGridSorteios", "Sorteio")',
        BuscaGridTodosSorteios: '@Url.Action("BuscaGridTodosSorteios", "Sorteio")',
        Vencedores: '@Url.Action("Winners", "Sorteio")',
        VencedoresUsuarios: '@Url.Action("WinnersUsuarios", "Sorteio")'
    }

    $("#Novo").click(function () {
        $.get(urlsSorteio.Create)
            .done(function (data) { $('#divContentSorteio').modal('open').html(data); })
            .fail(function (xhr) { erro(xhr.responseText) });
    });

    function escondeModal() {
        $("#divContentSorteio").modal('close');
    }

    var buscaTabelaSorteio = (function tabelaSorteio() {

        if (!verificaTodasSorteios) {
            $.get(urlsSorteio.BuscaGridSorteios)
                .done(function (data) {
                    $("#tabelaSorteios").html(data);
                }).fail(function (xhr) { erro(xhr.responseText) });
        } else {
            $.get(urlsSorteio.BuscaGridTodosSorteios)
                .done(function (data) {
                    $("#tabelaSorteios").html(data);
                }).fail(function (xhr) { erro(xhr.responseText) });
        }
        return tabelaSorteio;
    })();

    $("#MudarTabela").click(function () {
        if (verificaTodasSorteios) {
            verificaTodasSorteios = false;
            $("#MudarTabela").attr("data-tooltip", "Todos Sorteios");
        } else {
            verificaTodasSorteios = true;
            $("#MudarTabela").attr("data-tooltip", "Ativos");
        }
        $("#tabelaSorteios").fadeOut();
        buscaTabelaSorteio();
        $("#tabelaSorteios").fadeIn();
    });

    function editar(id) {
        $.post(urlsSorteio.Edit, {
            Id: id
        }).done(function (data) {
            escondeModal();
            $('#divContentSorteio').modal('open').html(data);
        }).fail(function (xhr) { erro(xhr.responseText) });
    };

    function detalhar(id) {
        $.get(urlsSorteio.Details, {
            id: id
        }).done(function (data) {
            escondeModal();
            $('#divContentSorteio').modal('open').html(data);
        }).fail(function (xhr) { erro(xhr.responseText) });
    };

    function deletar(id) {
        if (!confirm("Deseja realmente Excluir esse sorteio?")) return;

        $.get(urlsSorteio.Delete, {
            id: id
        }).done(function () {
            buscaTabelaSorteio();
        }).fail(function (xhr) {
            erro(xhr.responseText);
        });
    };

    function sairSorteio(idSorteio, idUsuario) {
        if (!confirm("Deseja realmente deixar de participar deste sorteio?")) return;

        $.post('@Url.Action("DeletarParticipante","SorteioParticipantes")', {
            idSorteio: idSorteio,
            idUsuario: idUsuario
        }).done(function (data) {
            sucesso(data);
            buscaTabelaSorteio();
        }).fail(function (xhr) {
            erro(xhr.responseText);
        });
    };

    function deletarSorteioParticipante(idSorteio, idUsuario) {
        if (!confirm("Deseja realmente deixar de participar deste sorteio?")) return;

        $.post('@Url.Action("DeletarParticipante","SorteioParticipantes")', {
            idSorteio: idSorteio,
            idUsuario: idUsuario
        }).done(function (data) {
            sucesso(data);
            buscaTabelaSorteio();
            setTimeout(function () { detalhar(idSorteio); }, 100);
        }).fail(function (xhr) {
            erro(xhr.responseText);
        });
    };

    function sortearNovamente(idSorteio) {
        $.get(urlsSorteio.Drawlots, {
            idSorteio: idSorteio
        }).done(function (data) {
            escondeModal();
            buscaTabelaSorteio();
            setTimeout(function () { $('#divContentSorteio').modal('open').html(data); }, 1000);
        }).fail(function (xhr) { erro(xhr.responseText) });
    };

    function vencedores(id) {
        $.get(urlsSorteio.Vencedores, {
            idSorteio: id
        }).done(function (data) {
            escondeModal();
            $('#divContentSorteio').modal('open').html(data);
        }).fail(function (xhr) { erro(xhr.responseText) });
    };

    function vencedoresUsuario(id) {
        $.get(urlsSorteio.VencedoresUsuarios, {
            idSorteio: id
        }).done(function (data) {
            escondeModal();
            $('#divContentSorteio').modal('open').html(data);
        }).fail(function (xhr) { erro(xhr.responseText) });
    };

    function sortear(id) {
        $.get(urlsSorteio.Drawlots, {
            idSorteio: id
        }).done(function (data) {
            buscaTabelaSorteio();
            setTimeout(function () { $('#divContentSorteio').modal('open').html(data); }, 100);
        }).fail(function (xhr) {
            Materialize.toast('' + xhr.responseText + '', 4000, 'rounded red');
        });
    };

    function participar(idSorteio, idUsuario) {
        if (!confirm("Deseja realmente participar deste sorteio?")) return;

        $.post('@Url.Action("Participar","SorteioParticipantes")', {
            idSorteio: idSorteio,
            idUsuario: idUsuario
        }).done(function (data) {
            sucesso(data);
            buscaTabelaSorteio();
        }).fail(function (xhr) {
            erro(xhr.responseText);
        });
    };

</script>