Hades.Web/ViewModels/CampanhaViewModel.cs
using Hades.Domain.Entities;
using System;
using System.Collections.Generic;

namespace Hades.Web.ViewModels
{
    public class CampanhaViewModel
    {
        public CampanhaViewModel()
        {
            Participantes = new List<CampanhaParticipanteViewModel>();
        }

        public CampanhaViewModel(CampanhaDto campanhaDto)
        {
            IdCampanha = campanhaDto.IdCampanha;
            DescCampanha = campanhaDto.DescCampanha;
            DataCadastro = campanhaDto.DataCadastro;
            DataLimite = campanhaDto.DataLimite;
            ValorCampanha = campanhaDto.ValorCampanha;
            IndAtivo = campanhaDto.IndAtivo;
            IdCriador = campanhaDto.IdCriador;
            NumeroParticipantes = campanhaDto.NumeroParticipantes;
            Participantes = new List<CampanhaParticipanteViewModel>();
        }

        public int IdCampanha { get; set; }
        public string DescCampanha { get; set; }
        public DateTime DataCadastro { get; set; }
        public DateTime DataLimite { get; set; }
        public decimal ValorCampanha { get; set; }
        public bool IndAtivo { get; set; }
        public int IdCriador { get; set; }
        public int NumeroParticipantes { get; set; }
        public string IndParticipante { get; set; }
        public string DataFormatada => $"{DataLimite:dd/MM/yyyy}";
        public string DataCadFormatada => $"{DataCadastro:dd/MM/yyyy}";

        public List<CampanhaParticipanteViewModel> Participantes { get; set; } 
    }
}

Hades.Web/Controllers/CampanhaController.cs
using Hades.Application.Interface;
using Hades.Domain.Entities;
using Hades.Web.ViewModels;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Hades.Web.Controllers
{
    public class CampanhaController : BaseController
    {
        private readonly ICampanhaAppService _campanhaAppService;
        private readonly ICampanhaParticipanteAppService _campanhaParticipanteAppService;
        private readonly IUsuarioAppService _usuarioAppService;

        public CampanhaController(ICampanhaAppService campanhaAppService, ICampanhaParticipanteAppService campanhaParticipanteAppService, IUsuarioAppService usuarioAppService)
        {
            _campanhaAppService = campanhaAppService;
            _campanhaParticipanteAppService = campanhaParticipanteAppService;
            _usuarioAppService = usuarioAppService;
        }

        public ActionResult Index()
        {
            ViewBag.NomeUsuario = Session["Nome"].ToString();
            return View();
        }

        public ActionResult BuscaGridCampanhas()
        {
            var campanhaViewModel = _campanhaAppService.GetCampanhas((int)Session["IdUsuario"]);
            if (!campanhaViewModel.IsSuccessStatusCode)
                return ErrorMessage("Erro ao trazer campanhas");
            var campanha = JsonConvert.DeserializeObject<IEnumerable<CampanhaViewModel>>(campanhaViewModel.Content.ReadAsStringAsync().Result);
            return View("_TabelaCampanha", campanha);
        }

        public ActionResult BuscaGridTodasCampanhas()
        {
            var campanhaViewModel = _campanhaAppService.GetTodasCampanhas((int)Session["IdUsuario"]);
            if (!campanhaViewModel.IsSuccessStatusCode)
                return ErrorMessage("Erro ao trazer campanhas");
            var campanha = JsonConvert.DeserializeObject<IEnumerable<CampanhaViewModel>>(campanhaViewModel.Content.ReadAsStringAsync().Result);
            return View("_TabelaCampanha", campanha);
        }

        public ActionResult Details(int idCampanha)
        {
            var campanha = _campanhaAppService.GetCampanha(idCampanha);
            if (!campanha.IsSuccessStatusCode)
                return ErrorMessage("Erro ao trazer Campanha");
            var mostraCampanha =
                JsonConvert.DeserializeObject<CampanhaViewModel>(campanha.Content.ReadAsStringAsync().Result);

            return View(mostraCampanha);
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult CreateConfirmed(CampanhaDto campanha)
        {
            var response = _campanhaAppService.Post(campanha);
            return response.IsSuccessStatusCode ? Json("OK") : ErrorMessage("Erro ao criar Campanha");
        }

        public ActionResult Edit(int idCampanha)
        {
            var response = _campanhaAppService.GetCampanha(idCampanha);
            if (!response.IsSuccessStatusCode)
                return ErrorMessage("Erro ao trazer campanha");
            var campanha = JsonConvert.DeserializeObject<CampanhaViewModel>(response.Content.ReadAsStringAsync().Result);

            return View(campanha);
        }

        public ActionResult EditConfirmed(CampanhaDto campanha)
        {
            var response = _campanhaAppService.Put(campanha);
            return response.IsSuccessStatusCode ? Json("OK") : ErrorMessage("Erro ao editar campanha");
        }

        public ActionResult Delete(int idCampanha)
        {
            var retorno = _campanhaAppService.Delete(idCampanha);
            return !retorno.IsSuccessStatusCode ? ErrorMessage("Erro ao deletar campanha") : Json("OK");
        }
    }
}

Hades.Web/Controllers/CampanhaParticipanteController.cs
using Hades.Application.Interface;
using Hades.Domain.Entities;
using Hades.Web.ViewModels;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Hades.Web.Controllers
{
    public class CampanhaParticipanteController : BaseController
    {
        private readonly ICampanhaParticipanteAppService _campanhaParticipanteAppService;

        public CampanhaParticipanteController(ICampanhaParticipanteAppService campanhaParticipanteAppService)
        {
            _campanhaParticipanteAppService = campanhaParticipanteAppService;
        }

        public ActionResult Participar(int idCampanha, int idUsuario)
        {
            var campanha = new CampanhaDto { IdCampanha = idCampanha, IdCriador = idUsuario };

            var response = _campanhaParticipanteAppService.Post(campanha);
            return !response.IsSuccessStatusCode 
                ? ErrorMessage("Erro ao ativar participante, tente novamente") 
                : Json("Sucesso, participante incluido com sucesso!", JsonRequestBehavior.AllowGet);
        }

        public IEnumerable<CampanhaParticipanteViewModel> Get(int idCampanha)
        {
            var response = _campanhaParticipanteAppService.Get(idCampanha);
            var participantes =
                JsonConvert.DeserializeObject<IEnumerable<CampanhaParticipanteViewModel>>(response.Content.ReadAsStringAsync().Result);
            return participantes;
        }

        public ActionResult DeletarParticipante(int idCampanha, int idUsuario)
        {
            var response = _campanhaParticipanteAppService.Delete(idUsuario, idCampanha);
            return !response.IsSuccessStatusCode 
                ? ErrorMessage("Erro ao alterar o usuario") 
                : Json("Sucesso, participante excluido com sucesso!", JsonRequestBehavior.AllowGet);
        }
    }
}

Hades.Web/Views/Campanha/Create.cshtml
@model Hades.Web.ViewModels.CampanhaViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutSemNavBar.cshtml";
}

<div class="row" style="margin-top: 12px">
    <div class="col s12">
        <div class="row">
            <h4>NOVO CAMPANHA</h4>

            @using (Html.BeginForm("CreateConfirmed", "Campanha", FormMethod.Post, new { @class = "well" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <div class="input-field col s12">
                        <textarea id="DescCampanha" name="DescCampanha" 
                                  class="materialize-textarea" maxlength="100" data-length="100" onkeypress="verificaCaracteres(this)"></textarea>
                        <label for="DescCampanha">DESCRIÇÃO:</label>
                    </div>
                    <div class="input-field col s6">
                        <input id="DataLimite" type="text" name="DataLimite" class="datepicker" />
                        <label for="DataLimite">DATA LIMITE</label>
                    </div>
                    <div class="input-field col s6">
                        <input id="Valor" name="Valor" type="text" maxlength="10" data-length="10">
                        <label for="Valor">VALOR R$</label>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="button" value="CRIAR" class="btn btn-confirm waves-effect" id="btnCriarCampanha" style="border-radius: 20px;" />
                        </div>
                    </div>
                </div>
            }
            <div style="margin-left: 110px; margin-top: -36px;">
                <button class="btn btn-default waves-effect" style="float: right" onclick="escondeModal()">CANCELAR</button>
            </div>
        </div>
    </div>
</div>
<script>

    var usuarioLogado = sessionStorage.getItem("IdUsuarioLogado");

    $(document).ready(function () {
        $('input#input_text, textarea#textarea1').characterCounter();
        $('#Valor').mask("###.###,##", { reverse: true });
        $('.datepicker').pickadate({
            monthsFull: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
            monthsShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
            weekdaysFull: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
            weekdaysShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
            today: 'Hoje',
            clear: 'Limpar',
            close: 'Pronto',
            labelMonthNext: 'Próximo mês',
            labelMonthPrev: 'Mês anterior',
            labelMonthSelect: 'Selecione um mês',
            labelYearSelect: 'Selecione um ano',
            selectMonths: true,
            selectYears: 15,
            format: 'dd/mm/yyyy'
        });
    });
    
    $("#btnCriarCampanha").click(function () {

        if ($("#DescCampanha").val().trim().length <= 3) {
            erro("Descrição tem que estar entre 3 até 100 caracteres");
            return false;
        }

        var dataInput = $("#DataLimite").val() != "" ? new Date($("#DataLimite").val()) : "";
        if (dataInput == "" || dataInput < new Date()) {
            erro("Data Limite deve ser maior que hoje");
            return false;
        }

        if ($("#Valor").val() <= 0) {
            erro("O valor tem que ser válida");
            return false;
        }

        $.post('@Url.Action("CreateConfirmed", "Campanha")', {
            DescCampanha: $("#DescCampanha").val().trim(),
            DataLimite: $("#DataLimite").val(),
            ValorCampanha: $("#Valor").val(),
            IdCriador: usuarioLogado
        }).done(function () {
            escondeModal();
            sucesso("Campanha cadastrada com Sucesso!");
            buscaTabelaCampanha();
        }).fail(function (xhr) {
            erro(xhr.responseText);
        });
    });

</script>

Hades.Web/Views/Campanha/Details.cshtml
@using Hades.Web.ViewModels
@model Hades.Web.ViewModels.CampanhaViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutSemNavBar.cshtml";
    var adm = (bool)Session["Administrador"];
    var usuarioLogado = Session["Nome"].ToString() != "" ? Session["Nome"] : "";
}
<div class="row" style="margin-top: 12px">
    <div class="col s12">
        <div class="row">
            <div>
                <h4>CAMPANHA</h4>
                <dl class="dl-horizontal">
                    <dt style="text-align: center;">NOME: @Html.DisplayFor(model => model.DescCampanha) </dt>
                    <dt style="text-align: center;">DATA LIMITE: @Html.DisplayFor(model => model.DataFormatada) </dt>
                    <dt style="text-align: center;">VALOR R$: @Html.DisplayFor(model => model.ValorCampanha) </dt>
                </dl>
            </div>
            <div>
                <h4>PARTICIPANTES</h4>
                <table class="striped">
                    <tr>
                        <th style="text-align: center;">NOME USUÁRIO</th>
                    </tr>
                    @if (Model.Participantes != null)
                    {
                        foreach (var participante in Model.Participantes)
                        {
                            <tr>
                                <td style="text-align: center;">
                                    @if (adm || participante.NomParticipante == usuarioLogado)
                                    {
                                        <a class="btn-floating red tooltipped" data-position="bottom" data-delay="50" data-tooltip="Desativar" style="width: 24px; height: 24px;">
                                            <i class="material-icons waves-effect" style="line-height: 25px; display: block; font-size: 1.1rem;"
                                               onclick="deletarParticipanteCampanha('@Model.IdCampanha', '@participante.IdUsuario')">perm_identity</i>
                                        </a>
                                    }
                                    @Html.DisplayFor(modelItem => participante.NomParticipante)
                                </td>
                            </tr>
                        }

                    }
                    else
                    {
                        <tr><td colspan="1" style="text-align: center;">Nenhum participante encontrado...</td></tr>
                    }
                </table>
            </div>
            <p></p>
            <div>
                <button class="btn btn-default waves-effect" style="width: -webkit-fill-available;" onclick="escondeModal()">Fechar</button>
            </div>
        </div>
    </div>
</div>

<script>
    function deletarParticipanteCampanha(idCampanha, idUsuario) {
        if (!confirm("Deseja realmente deletar participante desta campanha?")) return;

        $.post('@Url.Action("DeletarParticipante","CampanhaParticipante")', {
            idCampanha: idCampanha,
            idUsuario: idUsuario
        }).done(function (data) {
            sucesso(data);
            buscaTabelaCampanha();
            setTimeout(function () { detalhar(idCampanha); }, 100);
        }).fail(function (xhr) {
            erro(xhr.responseText);
        });
    };
</script>

Hades.Web/Views/Campanha/Edit.cshtml
@model Hades.Web.ViewModels.CampanhaViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutSemNavBar.cshtml";
}

<div class="row" style="margin-top: 12px">
    <div class="col s12">
        <div class="row">

            <h4>EDITAR CAMPANHA</h4>

            @using (Html.BeginForm("EditConfirmed", "Campanha", FormMethod.Post, new { @class = "col s12" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    @Html.HiddenFor(model => model.IdCampanha, new { htmlAttributes = new { @id = "IdCampanha" } })

                    <div class="input-field col s12">
                        <textarea id="DescCampanha" name="DescCampanha" class="materialize-textarea" maxlength="100" data-length="100"
                                  onkeypress="verificaCaracteres(this)">@Model.DescCampanha</textarea>
                        <label for="DescCampanha">DESCRIÇÃO:</label>
                    </div>

                    <div class="input-field col s6">
                        <input id="DataCadastro" style="text-align: center;" type="text" min="@DateTime.Now" name="DataCadastro" class="datepicker" 
                               value="@Model.DataCadastro.ToShortDateString()" readonly="readonly"/>
                        <label for="DataCadastro">DATA CADASTRO</label>
                    </div>

                    <div class="input-field col s6">
                        <input id="DataLimite" style="text-align: center;" type="text" name="DataLimite" min="@DateTime.Now" class="datepicker" 
                               value="@Model.DataLimite.ToShortDateString()" />
                        <label for="DataLimite">DATA LIMITE</label>
                    </div>

                    <div class="input-field col s6">
                        <input id="ValorCampanha" name="ValorCampanha" type="text" maxlength="10" data-length="10" value="@Model.ValorCampanha">
                        <label for="ValorCampanha">VALOR R$:</label>
                    </div>
                    <div class="input-field col s6" style="height: 67px;" >
                        <input type="checkbox" id="IndAtivo" name="IndAtivo" @(Model.IndAtivo ? "checked" : string.Empty) />
                        <label for="IndAtivo" style="color: black; font-weight: bold; ">ATIVA</label>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button id="btnEditarCampanha" class="btn btn-confirm waves-effect" style="float: left;">SALVAR</button>
                        </div>
                    </div>
                </div>

            }
            <div style="margin-left: 110px; margin-top: -36px;">
                <button class="btn btn-default waves-effect" style="float: right; margin-top: inherit;" onclick="escondeModal()">CANCELAR</button>
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        $('#Valor').mask("###.###,##", { reverse: true });
        $('input#input_text, textarea#textarea1').characterCounter();

        $('.datepicker').pickadate({
            monthsFull: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
            monthsShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
            weekdaysFull: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
            weekdaysShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
            today: 'Hoje',
            clear: 'Limpar',
            close: 'Pronto',
            labelMonthNext: 'Próximo mês',
            labelMonthPrev: 'Mês anterior',
            labelMonthSelect: 'Selecione um mês',
            labelYearSelect: 'Selecione um ano',
            selectMonths: true,
            selectYears: 15,
            format: 'dd/mm/yyyy'
        });
    });

    $("#btnEditarCampanha").click(function (e) {
        e.preventDefault();

        if (!$("#DescCampanha").val().trim()) {
            erro("Descrição não pode ser vazio");
            return false;
        }

        if (!$("#ValorCampanha").val()) {
            erro("Valor não pode ser vazio");
            return false;
        }

        var dataInput = $("#DataLimite").val() != "" ? new Date($("#DataLimite").val()) : "";

        if (dataInput == "" || dataInput < new Date()) {
            erro("Data da Campanha deve ser maior que hoje");
            return false;
        }

        var campanha =
        {
            IdCampanha: $("#IdCampanha").val(),
            DescCampanha: $("#DescCampanha").val().trim(),
            DataLimite: $("#DataLimite").val(),
            IndAtivo: $("#IndAtivo").prop("checked"),
            ValorCampanha: $("#ValorCampanha").val()
        };

        $.post('@Url.Action("EditConfirmed", "Campanha")', { campanha: campanha })
            .done(function () {
                sucesso("Cadastro atualizado com sucesso");
                escondeModal();
                buscaTabelaCampanha();
            }).fail(function (xhr) {
                erro(xhr.responseText);
        });
    });

</script>

Hades.Web/Views/Campanha/Index.cshtml
@using Hades.Web.ViewModels
@model IEnumerable<Hades.Web.ViewModels.CampanhaViewModel>

@{
    ViewBag.Title = "Index";
    Layout = (bool)Session["Administrador"] ? "~/Views/Shared/_Layout.cshtml" : "~/Views/Shared/_LayoutUsuario.cshtml";
    var mensagem = TempData["mensagem"]?.ToString() ?? "";
}

<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <div style="background-color: white; padding: 10px; border-radius: 15px; box-shadow: 0 0 30px black; margin-top: 2%;">
        <div style="float: left;">
            <a class="btn-floating red tooltipped waves-effect" data-position="bottom" data-delay="50" data-tooltip="Criar Sorteio" style="top: 15px;">
                <i class="material-icons" id="Novo">playlist_add</i>
            </a>

            <a class="btn-floating blue-grey tooltipped" id="MudarTabela" data-position="bottom" data-delay="50" data-tooltip="Todas Campanhas" style="top: 15px;">
                <i class="material-icons waves-effect">format_align_justify</i>
            </a>
        </div>
        <h4>LISTA DE COMPANHAS</h4>
        <div id="tabela">
            <div id="tabelaCampanha"></div>
        </div>
    </div>
</div>

<div id="divContentCampanhaDetail" class="modal modal-formatada-detail"></div>
<div id="divContentCampanha" class="modal modal-formatada"></div>

<script>

    var verificaTodasCampanhas = false;

    $(".modal-overlay").on("click", function () {
        $(this).hide();
    });

    var mensagemAviso = '@(!string.IsNullOrEmpty(mensagem)?mensagem:"")';

    $(document).ready(function () {
        $('.modal').modal();
        $('.tooltipped').tooltip({ delay: 50 });
        $('input#input_text, textarea#textarea1').characterCounter();
    });

    var urlsCampanha = {
        Edit: '@Url.Action("Edit")',
        Details: '@Url.Action("Details")',
        Delete: '@Url.Action("Delete")',
        Create: '@Url.Action("Create")',
        BuscaTabelaCampanhas: '@Url.Action("BuscaGridCampanhas")',
        BuscaTabelaTodasCampanhas: '@Url.Action("BuscaGridTodasCampanhas")',
        Participar: '@Url.Action("Participar","CampanhaParticipante")',
        SairCampanha: '@Url.Action("DeletarParticipante","CampanhaParticipante")'
    }

    var buscaTabelaCampanha = (function tabelaCampanha() {

        if (!verificaTodasCampanhas) {
            $.get(urlsCampanha.BuscaTabelaCampanhas)
                .done(function(data) {
                    $("#tabelaCampanha").html(data);
                }).fail(function(xhr) { erro(xhr.responseText); });
        } else {
            $.get(urlsCampanha.BuscaTabelaTodasCampanhas)
                .done(function (data) {
                    $("#tabelaCampanha").html(data);
                }).fail(function (xhr) { erro(xhr.responseText); });
        }


        return tabelaCampanha;
    })();

    mensagem(mensagemAviso);

    $("#MudarTabela").click(function() {
        if (verificaTodasCampanhas) {
            verificaTodasCampanhas = false;
            $("#MudarTabela").attr("data-tooltip", "Todas Campanhas");
        } else {
            verificaTodasCampanhas = true;
            $("#MudarTabela").attr("data-tooltip", "Ativos");
        }
        $("#tabelaCampanha").fadeOut();
        buscaTabelaCampanha();
        $("#tabelaCampanha").fadeIn();
    });

    $("#Novo").click(function () {
        $.get(urlsCampanha.Create)
            .done(function (data) { $('#divContentCampanha').modal('open').html(data); })
            .fail(function (xhr) { erro(xhr.responseText) });
    });

    function editar(id) {
        $.get(urlsCampanha.Edit, {
            idCampanha: id
        }).done(function (data) {
            escondeModal();
            $('#divContentCampanha').modal('open').html(data);
        }).fail(function (xhr) { erro(xhr.responseText) });
    };

    function detalhar(id) {
        $.get(urlsCampanha.Details, {
            idCampanha: id
        }).done(function (data) {
            escondeModal();
            $('#divContentCampanhaDetail').modal('open').html(data);
        }).fail(function (xhr) { erro(xhr.responseText) });
    };

    function desativar(idCampanha) {
        if (!confirm("Deseja realmente Desativar essa Campanha?")) return;

        $.get(urlsCampanha.Delete, {
            idCampanha: idCampanha
        }).done(function () {
            buscaTabelaCampanha();
        }).fail(function (xhr) {
            erro(xhr.responseText);
        });
    };

    var userLog = sessionStorage.getItem('IdUsuarioLogado');

    function participar(idCampanha, idUsuario) {
        if (!confirm("Deseja realmente participar desta Campanha?")) return;

        $.post(urlsCampanha.Participar, {
            idCampanha: idCampanha,
            idUsuario: idUsuario
        }).done(function (data) {
            sucesso(data);
            buscaTabelaCampanha();
        }).fail(function (xhr) {
            erro(xhr.responseText);
        });
    };

    function sairCampanha(idCampanha, idUsuario) {
        if (!confirm("Deseja realmente deixar de participar desta campanha?")) return;

        $.post(urlsCampanha.SairCampanha, {
            idCampanha: idCampanha,
            idUsuario: idUsuario
        }).done(function (data) {
            sucesso(data);
            buscaTabelaCampanha();
        }).fail(function (xhr) {
            erro(xhr.responseText);
        });
    };

    function escondeModal() {
        $("#divContentCampanha").modal('close');
        $("#divContentCampanhaDetail").modal('close');
    }

</script>

Hades.Web/Views/Campanha/_TabelaCampanha.cshtml
@using Hades.Web.ViewModels
@model IEnumerable<Hades.Web.ViewModels.CampanhaViewModel>

@{
    Layout = null;
    var adm = (bool)Session["Administrador"];
    var usuarioLogado = Session["Nome"].ToString() != "" ? Session["Nome"].ToString() : "";
    var idUsuarioLogado = (int)Session["IdUsuario"];
}

<table class="striped responsive-table">
    <thead>
        <tr>
            <th style="text-align: center; text-align: center;">Descrição:</th>
            <th style="text-align: center; text-align: center; width: 220px;">Data Limite:</th>
            <th style="text-align: center; text-align: center; width: 220px;">Valor R$:</th>
            <th style="text-align: center; text-align: center; width: 100px;">Participantes:</th>
            <th style="text-align: center; text-align: center; width: 140px;">Ações:</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (var campanha in Model)
            {
                <tr @(campanha.IndAtivo == false ? "style=color:#f00" : "")>
                    <td> @Html.DisplayFor(modelItem => campanha.DescCampanha) </td>
                    <td style="text-align: center; width: 220px;"> @Html.DisplayFor(modelItem => campanha.DataFormatada) </td>
                    <td style="text-align: center; width: 220px;"> @Html.DisplayFor(modelItem => campanha.ValorCampanha) </td>
                    <td style="text-align: center; width: 220px;"> @Html.DisplayFor(modelItem => campanha.NumeroParticipantes) </td>
                    @if (usuarioLogado != "")
                    {
                        <td style="padding: 0; text-align: center;">
                            <div>
                                <ul>
                                    <li>
                                        <a class="btn-floating grey darken-3 tooltipped" data-position="bottom" data-delay="50" data-tooltip="Detalhar">
                                            <i class="material-icons waves-effect" onclick="detalhar('@campanha.IdCampanha')">description</i>
                                        </a>
                                        @if (campanha.IndAtivo)
                                        {
                                            if (campanha.DataLimite >= DateTime.Today)
                                            {
                                                if (campanha.IndParticipante == "N")
                                                {
                                                    <a class="btn-floating green darken-3">
                                                        <i class="material-icons tooltipped waves-effect" data-position="bottom" data-delay="50" data-tooltip="Participar"
                                                           onclick="participar('@campanha.IdCampanha', '@idUsuarioLogado')">add_circle_outline</i>
                                                    </a>
                                                }
                                                else
                                                {
                                                    <a class="btn-floating red darken-3">
                                                        <i class="material-icons tooltipped waves-effect" data-position="bottom" data-delay="50"
                                                           data-tooltip="Sair Campanha" onclick="sairCampanha('@campanha.IdCampanha', '@idUsuarioLogado')">remove_circle_outline</i>
                                                    </a>
                                                }
                                            }
                                            if (adm || campanha.IdCriador == idUsuarioLogado)
                                             {
                                                 <a class="btn-floating red darken-4 tooltipped" data-position="bottom" data-delay="50" data-tooltip="Desativar">
                                                     <i class="material-icons waves-effect" onclick="desativar('@campanha.IdCampanha')">delete</i>
                                                 </a>
                                                 if (campanha.NumeroParticipantes == 0)
                                                 {
                                                     <a class="btn-floating orange tooltipped" data-position="bottom" data-delay="50" data-tooltip="Editar">
                                                         <i class="material-icons waves-effect" onclick="editar(@campanha.IdCampanha)">mode_edit</i>
                                                     </a>
                                                 }
                                             }
                                        }
                                    </li>
                                </ul>
                            </div>
                        </td>
                    }
                </tr>
            }
        }
        else
        {
            <tr><td colspan="9" style="text-align: center">Nenhum registro encontrado</td></tr>
        }
    </tbody>
</table>

<script>
    $(document).ready(function () {
        $('.modal').modal();
        $('.tooltipped').tooltip({ delay: 50 });
    });
</script>