Hades.Web/ViewModels/VotacaoViewModel.cs
namespace Hades.Web.ViewModels
{
    public class VotacaoViewModel
    {
        public int IdEnquete { get; set; }
        public int IdUsuario { get; set; }
        public string Enquete { get; set; }
        public string NomeUsuario { get; set; }
        public string Justificativa { get; set; }
        public bool TipoVoto { get; set; }
        public string IndicadorCadastro { get; set; }
        public string IndicadorTipoVoto => TipoVoto ? "S" : "N";
    }
}

Hades.Web/Controllers/VotacaoController.cs
using Hades.Application.Interface;
using Hades.Domain.Entities;
using System;
using System.Web.Mvc;

namespace Hades.Web.Controllers
{
    public class VotacaoController : BaseController
    {
        private readonly IVotacaoAppService _votacaoAppService;

        public VotacaoController(IVotacaoAppService votacaoAppService)
        {
            _votacaoAppService = votacaoAppService;
        }

        // GET: Votacao/Create
        public ActionResult Create(Votacao votacao)
        {
            return View(votacao);
        }

        // POST: Votacao/Create
        [HttpPost]
        public ActionResult CreateConfirmed(Votacao votacao)
        {
            try
            {
                var response = votacao.IndicadorCadastro == "S" ? _votacaoAppService.Post(votacao) : _votacaoAppService.Put(votacao);

                return !response.IsSuccessStatusCode 
                    ? ErrorMessage("Erro ao efetuar votação, tente novamente") 
                    : Json("Ok");
            }
            catch(Exception e)
            {
                return ErrorMessage("Falha ao efetuar votação, " + e.Message);
            }
        }
    }
}

Hades.Web/Views/Votacao/Create.cshtml
@model Hades.Domain.Entities.Votacao

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutSemNavBar.cshtml";
}

<div class="row" style="margin-top: 12px">
    <div class="col s12">
        <div class="row">

            @using (Html.BeginForm("CreateConfirmed", "Votacao"))
            {
                @Html.AntiForgeryToken()

                <div class="input-field col s12">
                    <input id="Titulo" name="Titulo" type="text" maxlength="20" value="@Model.Enquete" readonly="readonly" style="text-align: center;">
                    <label for="Titulo">TITÚLO ENQUETE:</label>
                </div>

                <div class="form-horizontal">
                    <h4>VOTAÇÃO</h4>
                    <div class="input-field col s12">
                        <textarea id="Justificativa" name="Justificativa" class="materialize-textarea" maxlength="200" data-length="200"
                                  onkeypress="verificaCaracteres(this)">@Model.Justificativa</textarea>
                        <label for="Justificativa">JUSTIFICATIVA DO VOTO:</label>
                    </div>

                    <div class="input-field col s12" style="width: auto; position: relative; margin-top: 0; margin-bottom: 10px; left: 58px; float: left;">
                        <input name="TipoVoto" type="radio" id="Favor" value="true" style="margin-left: 35px;" checked />
                        <label for="Favor">FAVOR</label>

                        <input name="TipoVoto" type="radio" id="Contra" value="false" style="margin-left: 20px; position: inherit;" />
                        <label for="Contra">CONTRA</label>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="button" id="Votar" value="VOTAR" class="btn btn-confirm waves-effect" 
                                   style="width: -webkit-fill-available;border-radius: 20px;top: 22px;position: relative;" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        if ('@Model.IndicadorTipoVoto' == "S")
            $("#Favor").prop("checked", true);
        else
            $("#Contra").prop("checked", true);

        $('input#input_text, textarea#textarea1').characterCounter();
    });

    var idEnquete = '@Model.IdEnquete';

    var urlsVotacao = {
        create: '@Url.Action("CreateConfirmed", "Votacao")'
    }

    var indicadorCadastro = '@Model.IndicadorCadastro';

    $("#Votar").click(function (e) {
        e.preventDefault(); //cancela o post


        if ($("#Justificativa").val().length <= 10 && $("#Contra").prop("checked", true)) {
            erro("Justificativa deve conter dentre 10 à 200 caracteres");
            return false;
        }

        $.post(urlsVotacao.create, {
            IdEnquete: idEnquete,
            IdUsuario: sessionStorage.getItem('IdUsuarioLogado'),
            Justificativa: $("#Justificativa").val(),
            IndicadorCadastro: indicadorCadastro,
            TipoVoto: $("[name=TipoVoto]:checked").val()
        }).done(function () {
            escondeModal();
            sucesso("Voto efetuado com Sucesso!");
            buscaTabelaEnquete();
        }).fail(function (xhr) {
            erro(xhr.responseText);
        });
    });

</script>